package capstone_project.common.enums;

public enum OrderStatusEnum {
    PENDING,
    PROCESSING,
    CANCELLED,
    CONTRACT_DRAFT,
    CONTRACT_DENIED,
    CONTRACT_SIGNED,
    ON_PLANNING,
    ASSIGNED_TO_DRIVER,
    DRIVER_CONFIRM,
    PICKED_UP,
    SEALED_COMPLETED,
    ON_DELIVERED,
    ONGOING_DELIVERED,
    IN_DELIVERED,
    IN_TROUBLES,
    RESOLVED,
    COMPENSATION,
    DELIVERED,
    SUCCESSFUL,
    REJECT_ORDER,
    RETURNING,
    RETURNED
}
