package capstone_project.common.enums;

public enum OrderStatusEnum {
    PENDING,
    PROCESSING,
    CANCELLED,
    CONTRACT_DRAFT,
    CONTRACT_DENIED,
    CONTRACT_SIGNED,
    ON_PLANNING,
    ASSIGNED_TO_DRIVER,
    FULLY_PAID,
    PICKING_UP,
    ON_DELIVERED,
    ONGOING_DELIVERED,
    IN_TROUBLES,
    RESOLVED,
    COMPENSATION,
    DELIVERED,
    SUCCESSFUL,
    REJECTED,
    RETURNING,
    RETURNED
}
