package capstone_project.dtos.response.user;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serial;
import java.io.Serializable;

/**
 * Response DTO returned when admin creates a new driver.
 * Contains the driver info plus the temporary password for the driver to use on first login.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class DriverCreatedResponse implements Serializable {
    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * The created driver information
     */
    private DriverResponse driver;

    /**
     * Temporary password generated by the system.
     * Admin should share this with the driver securely.
     * Driver must change this password on first login.
     */
    private String temporaryPassword;

    /**
     * Login instructions for the driver
     */
    private String loginInstructions;
}
