-- Add metadata fields to distance_rules for dynamic management
ALTER TABLE distance_rules
ADD COLUMN display_order INT NOT NULL DEFAULT 0,
ADD COLUMN display_name VARCHAR(100),
ADD COLUMN is_base_price BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

-- Add indices for better query performance
CREATE INDEX idx_distance_rules_display_order ON distance_rules(display_order);
CREATE INDEX idx_distance_rules_status ON distance_rules(status);

-- Update existing distance rules with calculated metadata
-- The display_name will be auto-generated by the smart calculation service
-- For now, set display_order based on from_km ascending
UPDATE distance_rules dr
SET display_order = (
    SELECT COUNT(*) 
    FROM distance_rules dr2 
    WHERE dr2.from_km < dr.from_km
);

-- Mark the first range (0-3.99) as base price
UPDATE distance_rules
SET is_base_price = TRUE
WHERE from_km = 0.00;

-- Add check constraint to ensure only one base price exists
CREATE UNIQUE INDEX idx_distance_rules_unique_base_price 
ON distance_rules(is_base_price) 
WHERE is_base_price = TRUE AND status = 'ACTIVE';

-- Add check constraint for valid status values
ALTER TABLE distance_rules
ADD CONSTRAINT chk_distance_rules_status 
CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED'));

-- Add comment for documentation
COMMENT ON COLUMN distance_rules.display_order IS 'Auto-calculated order for display in UI, based on from_km ascending';
COMMENT ON COLUMN distance_rules.display_name IS 'Auto-generated display name (e.g., "4KM ĐẦU", "5-15KM", ">100KM")';
COMMENT ON COLUMN distance_rules.is_base_price IS 'Auto-calculated flag indicating if this is the base price range (first range starting from 0)';
COMMENT ON COLUMN distance_rules.status IS 'Status of the distance rule (ACTIVE, INACTIVE, DELETED)';
